### ISSUE TITLE
Allow resources to contain subset of entity's properties

### ISSUE THREAD

**Issue by raraworks** [whitedigital-eu/entity-resource-mapper#13]
If i define a ApiResource that does not contain a property, that exists in database, i get an error:

`Property clientObjects does not exist in class App\\ApiResource\\ClassifierResource`

This is caused by [this line in package](https://github.com/whitedigital-eu/entity-resource-mapper/blob/3d9417772126aebfac62c8ae48cec5e0460f75a0/src/Mapper/EntityToResourceMapper.php#L262)

If i am going to have multiple different api resources that dont conform to entity properties, this will become an issue, as i need to define properties that are never going to be used.

We need to allow api resources to contain subset of entities properties, otherwise the mapper loses some of its value.

**Comment by raraworks** [comment]
there is an issue with data persistence, as in, what data should be used for properties that only exist in entity but not in api resource

**Comment by acirulis** [comment]
There is #[Ignore] attribute you can use on Entity property, it will be then ignored in mapper. It is also default behavior of Symfony built-in Serializer. https://symfony.com/doc/current/components/serializer.html#option-1-using-ignore-annotation

**Comment by raraworks** [comment]
But if there are multiple resources related to entity, and one of them requires this property, while the other one does not?

**Comment by acirulis** [comment]
Ok, until there is specific usecase, let's close this as Won't Fix. Also have to consider API Platform v3
